# Generated by Django 3.1.4 on 2022-01-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220125_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='other_address',
            new_name='address_line_3',
        ),
    ]
