# Generated by Django 3.1.4 on 2022-01-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220125_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_line_3',
            new_name='country',
        ),
    ]
