# Generated by Django 3.1.4 on 2022-01-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='color',
            new_name='size',
        ),
    ]
